"""empty message

Revision ID: 119450b64299
Revises: 7ad68a1dd7a7
Create Date: 2021-09-04 23:14:23.352734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '119450b64299'
down_revision = '7ad68a1dd7a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('production', sa.Column('zametki', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('production', 'zametki')
    # ### end Alembic commands ###
