"""empty message

Revision ID: 7ad68a1dd7a7
Revises: 7ef98fdee4ca
Create Date: 2021-09-04 22:38:18.579277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ad68a1dd7a7'
down_revision = '7ef98fdee4ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('production', sa.Column('long', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'production', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'production', type_='unique')
    op.drop_column('production', 'long')
    # ### end Alembic commands ###
